### ISSUE TITLE
How to use the php api?

### ISSUE THREAD

**Issue by makuulen** [binance/binance-connector-php#14]
Good afternoon. I program in php. I would like to access the exchange through your api. Before that, I traded on another exchange in the same way, the api was simple and clear there, but it's hard to figure it out, you need help. I understand that some kind of file is needed, it connects everywhere - vendor/autoload.php . What is it and how to download it? I don't understand. Help please.

**Comment by 2pd** [comment]
Please check the README file which contains the installation and basic instruction.  The example folder has the php scripts for each method, please feel free to try.

**Comment by aisling-2** [comment]
Due to lack of feedback, we're closing the issue for now, but feel free to reopen if there's more specific questions. Ty.
