### ISSUE TITLE
openssl_sign(): Supplied key param cannot be coerced into a private key

### ISSUE THREAD

**Issue by VicRejkia** [binance/binance-connector-php#16]
I implemented this package in my Laravel project and initialized it like this
```
            $client = new Spot([
                'key'  => config('binance.testnet.api_key'),
                'privateKey'  => config('binance.testnet.api_secret'),
                'baseURL' => 'https://testnet.binance.vision'
            ]);
```
a simple `$client->time()` returns the timecode. But if I want to send an order or want to get some account info, I will get this error:
`openssl_sign(): Supplied key param cannot be coerced into a private key`

What do I wrong?

**Comment by 2pd** [comment]
can you provide more details of the error message?

`privateKey` should be the private key file path in the client side.
