### ISSUE TITLE
SimpleEarn Endpoint Outdated

### ISSUE THREAD

**Issue by riancaag** [binance/binance-connector-php#29]
I want to use the new endpoints for simpleearn enabled in the Binance API since August 26, 2023, I have already tried to update the php library on my server but it still does not appear available, do you have any plans to update the library soon term? or you can help me update my library locally with the new simpleearn endpoints. I would appreciate your help.

![imagen](https://github.com/binance/binance-connector-php/assets/93340317/272251c7-9a15-4abb-9ffa-db8dfa8d7ebf)

**Comment by aisling-2** [comment]
Hi @riancaag, thanks for opening the issue, however unfortunately, we don't have the resources at the moment to update all the open repositories we have available in a timely manner.

**Comment by alplabin** [comment]
The endpoint have been updated in the latest release: [v1.7.0](https://github.com/binance/binance-connector-php/releases/tag/v1.7.0)
