### ISSUE TITLE
composer require binance/binance-connector-php issue

### ISSUE THREAD

**Issue by esonbest** [binance/binance-connector-php#3]
composer require binance/binance-connector-php 
Could not find a version of package binance/binance-connector-php matching   
  your minimum-stability (stable). Require it with an explicit version constr  
  aint allowing its desired stability.      

can you tell me the dependence   i should install.  (php 7.4.30 installed)

**Comment by 2pd** [comment]
can you provide a few info:
- what's your OS and version
- what's your composer version
- what's your php version

thanks

**Comment by esonbest** [comment]
@2pd  thank you for you help.
OS:  4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
PHP: PHP 8.0.19 (cli) (built: Jul 14 2022 20:03:09) ( NTS ),Zend Engine v4.0.19
Composer version 2.3.10 2022-07-13 15:48:23

**Comment by esonbest** [comment]
it seems it's okay now .
![1658200635391](https://user-images.githubusercontent.com/70562081/179657349-54b2cb16-4c57-4665-b931-b9e3efeb9c50.png)

**Comment by esonbest** [comment]
Thank you 2pd

**Comment by 2pd** [comment]
nice 😄
