### ISSUE TITLE
contribution guide

### ISSUE THREAD

**Issue by scherbak-electronics** [binance/binance-connector-php#30]
Is there any contribution guides? I want to implement connector for USDM-Futures, has some one already start working on that?

**Comment by aisling-2** [comment]
Hi @scherbak-electronics, there's no plan yet for a USDM-Futures connector using PHP.
Currently, we're only providing Futures connector in node.js, python and java langs, which are created separately from the Spot connector (different package manager).
This means that for PHP we also wouldn't include the futures product into this Github repository, but feel free to fork this repo and create your own project.
