### ISSUE TITLE
Fatal error after PHP update

### ISSUE THREAD

**Issue by arsmagic** [binance/binance-connector-php#7]
Fatal error: Uncaught Error: Class "Psr\Log\NullLogger" not found in XXX/vendor/binance/binance-connector-php/src/Binance/APIClient.php:73 Stack trace: #0 XXX/vendor/binance/binance-connector-php/src/Binance/Spot.php(35): Binance\APIClient->__construct() #1 MYscript: Binance\Spot->__construct() #2 {main} thrown in XXX/vendor/binance/binance-connector-php/src/Binance/APIClient.php on line 73

Any idea, what is the cause for the error? Just updated PHP 7.4 to PHP v8.1, updated and re-installed all the packages, and the previously working script still causes such an error....

**Comment by 2pd** [comment]
can you run:

`php -v`

and paste what you see.


Also can you run:

`composer dump-auto`

and see if it works.
